Homework 1 (adding HTML basic structure)
ok-technopolis-2020/Popok_Artem pull request #1
Opened 2020-10-08 23:44 UTC by pa-artem

2020-10-09 12:19 UTC, fromanywhere requested changes
Хорошо по aria, хорошо по идеям группировки, но я не согласен с иерархией menu > li настолько повсеместно

2020-10-09 12:19 UTC, fromanywhere commented on index.html
> +                <menu role="listitem" aria-label="&quot;HTML&quot; task">
Ну нет, в первый раз я еще мог согласиться на `<menu>`, хотя никогда не видел, чтобы туда клали интерактивные элементы, но тут уже явно перебор

2020-10-09 12:19 UTC, fromanywhere commented on index.html
> +                <menu role="listitem" aria-label="&quot;CSS&quot; task">
есть ли смысл в кавычках для читалок? Я кстати даже почти уверен, что html-сущности в атрибутах так не заработают

2020-10-09 12:19 UTC, fromanywhere commented on index.html
> +                        <label for="task2">CSS</label>
Здорово, что for!

2020-10-09 12:19 UTC, fromanywhere commented on index.html
> +                    <li>
ну вот сомнительно, что внутри элемента тут список

2020-10-15 11:48 UTC, pa-artem commented on index.html
> +                <menu role="listitem" aria-label="&quot;HTML&quot; task">
Я думал, что это семантический тег, но, как оказалось, это про контекстные меню. Попробовал убрать их сейчас.

2020-10-15 11:48 UTC, pa-artem commented on index.html
> +                <menu role="listitem" aria-label="&quot;CSS&quot; task">
Вроде как [работают](https://jsfiddle.net/63a0mnsv/), но, действительно, пользы от них тут никакой нет.

2020-10-16 12:53 UTC, fromanywhere approved these changes

2020-10-16 13:23 UTC, merged